# Generated by Django 4.0.6 on 2022-07-08 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_candidatesapplied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatesapplied',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatesapplied', to='job.job'),
        ),
    ]
