# Generated by Django 4.0.6 on 2022-07-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_availablity_job_duration_job_mode_job_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='mode',
            field=models.CharField(choices=[('Work from Home/Remote', 'Wfh'), ('On-site', 'On Site'), ('Hybrid Mode', 'Hybrid Mode')], default='Hybrid Mode', max_length=30, null=True),
        ),
    ]
