# Generated by Django 4.0.6 on 2022-07-12 04:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_job_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Web Development'), (2, 'PHP'), (3, 'SQL'), (4, 'JavaScript'), (5, 'Android Development')], max_length=50, null=True),
        ),
    ]
