# Generated by Django 4.0.6 on 2022-07-12 06:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Web Development'), (2, 'PHP'), (3, 'SQL'), (4, 'JavaScript'), (5, 'Android Development'), (6, 'IOS Development'), (7, 'Java'), (8, 'C/C++'), (9, 'Python'), (10, 'Cloud'), (11, 'Swift'), (12, 'Database Management'), (13, 'Network Security/Management'), (14, 'Dart'), (15, 'Image Processing'), (16, 'Deep Learning'), (17, 'Artificial Intelligence'), (18, 'Business Analytics'), (19, 'Blockchain'), (20, 'Cyber Security'), (21, 'Project Management'), (22, 'UI/UX')], max_length=50, null=True),
        ),
    ]
